# Generated by Django 5.1.7 on 2025-07-03 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_cliente_fecha_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total_final',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
