# Generated by Django 5.1.7 on 2025-07-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_alter_pedido_total_alter_pedido_total_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='completado',
            field=models.BooleanField(default=False),
        ),
    ]
