# Generated by Django 5.1.7 on 2025-07-16 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_empleado_pedido_empleado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='senia',
            new_name='seña',
        ),
    ]
