"""
Django settings for LucyApp project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
from decouple import config


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@%q7p6x@o00xb&k0-9&m41pfe%t$%#0bau1gix5f6og8=$$^ye'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['.onrender.com']


# Application definition

INSTALLED_APPS = [
    "jazzmin",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'import_export',
    'pedidos.apps.PedidosConfig',
    # 'pedidos',
    
                                             
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]



ROOT_URLCONF = 'LucyApp.urls'

TEMPLATES = [
    {   
        
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  # Esta línea es crucial
        
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LucyApp.wsgi.application'




DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT'),
    }
}



AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/Argentina/Buenos_Aires'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
# STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'pedidos/static'),
]
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

ADMIN_SITE_HEADER = "Administración de Lucy"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_SECURE = False  # True en producción con HTTPS

# LOGIN_URL = 'login'  # Nombre de la URL de login
# LOGIN_REDIRECT_URL = 'catalogo'  # Redirigir aquí después de login
# LOGOUT_REDIRECT_URL = 'login'  # Redirigir aquí después de logout
LOGIN_URL = '/accounts/login/'  # Si decides usar login más adelante
LOGIN_REDIRECT_URL = '/admin/'
LOGOUT_REDIRECT_URL = '/admin/login/'


JAZZMIN_SETTINGS = {
    "site_title": "LucyApp Admin",
    "site_header": "LucyApp",
    "site_brand": "LucyApp",
    "welcome_sign": "Bienvenid@ a LucyApp",
    "site_logo": "pedidos/img/logo-white.png",
    "site_icon": "pedidos/img/logo.png",  # favicon
    "site_logo_classes": "img-circle",
    "site_icon": "pedidos/img/logo.png",
    "user_avatar": "pedidos/img/logo-white.png",
  # logo como avatar

    # Modo oscuro
    "bootswatch_theme": "darkly", # uno de los temas bootstrap de bootswatch

    # Login
    "login_logo": "pedidos/img/logo.png",
    "login_logo_height": "180px",
    
    "custom_css": "pedidos/css/custom-admin.css",  # usamos css personalizado

    # Otros ajustes útiles
    "show_ui_builder": False,
}

STATICFILES_DIRS = [os.path.join(BASE_DIR, 'pedidos/static')]





